name: Main CI-pipeline

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4 
      with:
        dotnet-version: 8.0.x

    - name: Checkstyle
      run: dotnet format --verify-no-changes --check

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore /p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./TestResults/'
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: TestResults
        path: ./TestResults