name: Main CI-pipeline

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4 
      with:
        dotnet-version: 8.0.x

    - name: Checkstyle
      run: dotnet format ${{ github.workspace }}/SpaceBattle/SpaceBattle.sln --verify-no-changes

    - name: Restore dependencies
      run: dotnet restore ${{ github.workspace }}/SpaceBattle

    - name: Build
      run: dotnet build ${{ github.workspace }}/SpaceBattle --configuration Release --no-restore /p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test ${{ github.workspace }}/SpaceBattle --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./TestResults/'
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: TestResults
        path: ./TestResults
